# docker-compose.dev.yml
version: "3"

services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - 5438:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
